spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true

  cache:
    type: simple
    cache-names:
      - movieSearch
      - moviesByGenre
      - moviesByFirstLetter
      - movieDetails
      - autocompleteTitles
      - topRatedMovies
      - starDetails

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: groupone
    key-store-type: PKCS12
    key-alias: webproject

frontend:
  url: https://localhost:4200